### ISSUE TITLE
Player only sits facing south

### ISSUE THREAD

**Issue by esotericdesign** [mchorse/reads#1]
Since furniture added by mods (Sit, Bibliocraft or, in my case, Decocraft) is static, player's body only sits facing south, while the head rotates along with the camera.
Also, if I don't hold anything, all furniture I can sit down on renders transparent from the second and third person views, but it's okay.
Version 1.12.2, Mod version 0.3.2
![2020-01-05_04 21 25](https://user-images.githubusercontent.com/40729240/71773728-53afdc00-2f73-11ea-841e-6fffa019e575.png)
![2020-01-05_04 22 27](https://user-images.githubusercontent.com/40729240/71773729-5a3e5380-2f73-11ea-93da-65ef288fe86c.png)
![2020-01-05_04 22 50](https://user-images.githubusercontent.com/40729240/71773730-5ca0ad80-2f73-11ea-9101-df4197e9e87a.png)

**Comment by mchorse** [comment]
Fixed it, will be released in `0.4`.
